# Enable C++ support
language: cpp
cache: ccache

stages:
  - build
  - analysis
jobs:
  include:
    - stage: build
      dist: bionic
      env:
        - COMPILER=clang++-8
      script: ./support/tools/build
    - stage: build
      dist: bionic
      env:
        - COMPILER=g++
        - TYPE=Debug
      script: ./support/tools/build
    - stage: analysis
      dist: bionic
      env:
        - COMPILER=clang++-8
      script: ./support/tools/build-sanitizers

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./support/tools/install-tools; fi