# Enable C++ support
language: cpp

stages:
  - static analysis
  - build
  - address sanitizer
  - thread sanitizer
  - undefined behavior sanitizer

jobs:
  include:
    - stage: static analysis
      dist: bionic
      env: COMPILER=clang++-8
      script: ./support/tools/tidy
    - stage: build
      dist: bionic
      env: COMPILER=clang++-8
      script: ./support/tools/build
    - stage: build
      dist: bionic
      env: COMPILER=g++
      script: ./support/tools/build
    - stage: address sanitizer
      dist: bionic
      env: COMPILER=clang++-8
      script: ./support/tools/build-asan
    - stage: thread sanitizer
      dist: bionic
      env: COMPILER=clang++-8
      script: ./support/tools/build-tsan
    - stage: undefined behavior sanitizer
      dist: bionic
      env: COMPILER=clang++-8
      script: ./support/tools/build-ubsan

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./support/tools/install-tools; fi