# Enable C++ support
language: cpp

stages:
  - static analysis
  - build
  - address sanitizer
  - thread sanitizer
  - undefined behavior sanitizer

jobs:
  include:
    - stage: static analysis
      dist: bionic
      script: ./support/tools/tidy
    - stage: build
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - ninja-build
      env: COMPILER=clang++-7
      script: ./support/tools/build
    - stage: build
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env: COMPILER=g++-7
      script: ./support/tools/build
    - stage: address sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - ninja-build
      env: COMPILER=clang++-7
      script: ./support/tools/build-asan
    - stage: thread sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - ninja-build
      env: COMPILER=clang++-7
      script: ./support/tools/build-tsan
    - stage: undefined behavior sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - ninja-build
      env: COMPILER=clang++-7
      script: ./support/tools/build-ubsan

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository universe; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --allow-unauthenticated clang-7 clang-tools-7 libclang-common-7-dev libclang-7-dev libclang1-7 clang-tidy-7 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install conan; conan user ; fi