language: cpp
sudo: false

dist:
  - trusty
  - bionic

matrix:
  include:
    - os: linux
      env: CONFIG=Release TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=gcc
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=Debug
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=sanitize-address
    - os: linux
      env: CONFIG=Debug TOOLCHAIN=sanitize-leak