# Enable C++ support
language: cpp

stages:
  - static analysis
  - build
  - address sanitizer
  - thread sanitizer
  - undefined behavior sanitizer

jobs:
  include:
    - stage: static analysis
      dist: trusty
      script: ./support/tools/tidy
    - stage: build
      os: linux
      sudo: required
      dist: trusty
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - ninja-build
      env: COMPILER=clang++-8
      script: ./support/tools/build
    - stage: build
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env: COMPILER=g++-7
      script: ./support/tools/build
    - stage: address sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - ninja-build
      env: COMPILER=clang++-8
      script: ./support/tools/build-asan
    - stage: thread sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - ninja-build
      env: COMPILER=clang++-8
      script: ./support/tools/build-tsan
    - stage: undefined behavior sanitizer
      os: linux
      sudo: required
      dist: bionic
      before_install: false
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
            - ninja-build
      env: COMPILER=clang++-8
      script: ./support/tools/build-ubsan

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic main"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --allow-unauthenticated clang-8 clang-tools-8 libclang-common-8-dev libclang-8-dev libclang1-8 clang-tidy-8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install conan; conan user ; fi