#!/bin/sh

sudo apt-get update -qq

sudo apt-get install -y wget
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-xenial-8 main"
sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
sudo apt-get update -qq

sudo apt apt install -y --allow-unauthenticated libllvm8
sudo apt-get install -y --allow-unauthenticated \
             clang-8 clang-tools-8 clang-8-doc libclang-common-8-dev libclang-8-dev libclang1-8 clang-tidy-8
sudo apt-get install -y ninja-build cmake ccache llvm-8

# Project depedencies (non-conan)
sudo apt-get install -y libboost-filesystem-dev

wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_18_0.deb
sudo dpkg -i conan-ubuntu-64_1_18_0.deb
conan user
#conan profile update settings.compiler.libcxx=libstdc++11 default
