#!/bin/sh

sudo apt-get update -qq
sudo apt-get install -y --allow-unauthenticated clang-7 clang-tools-7 libclang-common-7-dev libclang-7-dev libclang1-7 clang-tidy-7
sudo apt-get install -y wget

sudo apt-get install -y libboost-filesystem-dev

wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_18_0.deb
sudo dpkg -i conan-ubuntu-64_1_18_0.deb
conan user
